name: Build and Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        EXIT_CODE=0
        while IFS= read -r file; do
          clang-format -style=file "$file" | diff -u "$file" -
          if [ $? -ne 0 ]; then
            EXIT_CODE=1
          fi
        done < <(find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)')
        exit $EXIT_CODE

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t low-level-navigator .

    - name: Run build inside Docker
      run: docker run --rm -v ${{ github.workspace }}:/workspace low-level-navigator 

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: low-level-navigator
        path: build/low-level-nav.uf2